language: elixir

dist: bionic
sudo: required

elixir:
  - '1.9.0'

otp_release:
  - '22.0'

addons:
  postgresql: '11'
  apt:
    packages:
      - postgresql-11
      - postgresql-client-11

env:
  - MIX_ENV=test

cache:
  directories:
    - _build
    - deps

before_install:
  - sudo sed -i -e 's/^#listen_addresses.*/listen_addresses = "*"/' /etc/postgresql/11/main/postgresql.conf
  - sudo sed -i -e 's/^port = 5433/port = 5432/' /etc/postgresql/11/main/postgresql.conf
  - sudo service postgresql restart 11

install:
  - mix local.hex --force
  - mix local.rebar --force

before_script:
  - cp config/travis.exs config/test.exs
  
script:
  - skip
